---
title: "analysis"
author: "Gabe Cederberg"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readr)
library(fivethirtyeight)
library(janitor)
library(ggthemes)
library(gt)
library(reprex)
library(magrittr)
library(stringr)
library(haven)
library(infer)
library(skimr)
library(tidyr)
library(readxl)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
a <- read_excel("HudsData.xlsx") %>% 
  select(stat = "...1",
         Adams:Winthrop) %>% 
  pivot_longer(cols = c("Adams", 
                        "Annenberg",
                        "Cabot",
                        "Currier",
                        "Dunster",
                        "Eliot",
                        "Kirkland",
                        "Leverett",
                        "Lowell",
                        "Mather",
                        "Pforzheimer",
                        "Quincy",
                        "Winthrop"),
               names_to = "house") %>% 
  pivot_wider(names_from = stat, 
              values_from = value) %>% 
  clean_names() 

a$confint[2] <- NA

b <- a %>% 
  mutate(upper = mean + confint,
         lower = mean - confint)
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}

# Plotting thank-you rates.

ggplot(b, aes(house, mean, fill = house)) +
  geom_col() +
  geom_errorbar(aes(x=house, ymin=lower, ymax=upper), width=0.3, colour="black", alpha=0.8, size=.3) + 
  theme_classic() +
  labs(x = "House", 
       y = "Thank-You Rate", 
        title = "Thank-You Rates in Each Harvard Dining Hall", 
        subtitle = "N = 525",
       caption="Error Bars represent 95% confidence intervals; 
       Annenberg error bar omitted due to small sample size.") +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 30, vjust= .7)) +
    scale_fill_viridis_d(option = "plasma")
  
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
# Thank-you rates ranked

ggplot(b, aes(reorder(house, -mean), mean, fill = house)) +
  geom_col() +
  geom_errorbar(aes(x=house, ymin=lower, ymax=upper), width=0.2, colour="black", alpha=0.7, size=.3) + 
  theme_classic() +
  labs(x = "House", 
       y = "Thank-You Rate", 
        title = "Thank-You Rates in Each Harvard Dining Hall", 
        subtitle = "Error bars show the 95% confidence interval; N = 525",
       caption="Error Bars represent 95% confidence intervals;
       Annenberg error bar omitted due to small sample size.") +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 30, vjust= .7)) +
    scale_fill_viridis_d(option = "E")


```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

# Bootstrap confidence intervals

a <- read_excel("CederbergHODPstudy.xlsx") %>% 
  clean_names() %>%
  select(house = "x1",
         pickups = "number_of_grill_orders_picked_up_w_huds_staff_present",
         thanks = "number_of_thank_yous",
         students = "number_of_students_in_each_house") %>% 
  filter(house != "Total") %>% 
  mutate(
    fail = pickups - thanks,
    pct = thanks / pickups) %>% 
  mutate(weighted = pct * (students / 6264))

lower <- function(n) {
  each_house <- tibble(thanks = c(
    rep(1, a$thanks[n]),
    rep(0, a$fail[n])))
  
  each_house %>% 
    rep_sample_n(size = a$pickups[n], reps = 1000, replace = TRUE) %>% 
  group_by(replicate) %>% 
  summarize(thanks_rate = (sum(thanks) / a$pickups[n])) %>% 
              pull(thanks_rate) %>% 
  quantile(c(0.025))
}

upper <- function(n) {
  each_house <- tibble(thanks = c(
    rep(1, a$thanks[n]),
    rep(0, a$fail[n])))
  
  each_house %>% 
    rep_sample_n(size = a$pickups[n], reps = 10000, replace = TRUE) %>% 
  group_by(replicate) %>% 
  summarize(thanks_rate = (sum(thanks) / a$pickups[n])) %>% 
              pull(thanks_rate) %>% 
  quantile(c(0.975))
}

bounds <- tibble(id = 1:13,
               lower = map(1:13, ~ lower(.)),
               upper = map(1:13, ~ upper(.))) %>% 
            unnest()

means <- a %>% 
  select(pct, house) %>% 
  mutate(id = c(1:13)) %>% 
  select(id, house, pct)

combined <- bounds %>% 
  left_join(means)


combined$lower[2] <- NA
combined$upper[2] <- NA
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}

# Bootstrap confidence intervals

ggplot(combined, aes(house, pct, fill = house)) +
  geom_col() +
  geom_errorbar(aes(x=house, ymin=lower, ymax=upper), width=0.3, colour="black", alpha=0.8, size=.3) + 
  theme_classic() +
  labs(x = "House", 
       y = "Thank-You Rate", 
        title = "Thank-You Rates in Each Harvard Dining Hall", 
        subtitle = "N = 525",
       caption="Error Bars represent 95% confidence intervals using 10,000 bootstrapped samples; 
       Annenberg error bars omitted due to small sample size (np < 10).", size = 0.05) +
    theme(legend.position = "none",
          axis.title.x = element_text(size = 12),
          axis.title.y = element_text(size = 12),
          axis.text.x = element_text(angle = 30, vjust= .7)) +
    scale_fill_viridis_d(option = "plasma")
```

